sudo: required
services:
  - docker
node_js:
  - "8"
before_install:
  - docker build -t sadhwanim/docker-react -f Dockerfile.dev .

script:
 - docker run sadhwanim/docker-react npm run test -- --coverage    
